############### Code to download new data to a file ##############

In [1]:
from pathlib import Path
import sys
# For Jupyter notebooks, use current working directory
project_root = Path.cwd()
sys.path.insert(0, str(project_root))

In [2]:
from alpaca.data.historical import StockHistoricalDataClient
from alpaca.data.requests import StockBarsRequest
from alpaca.data.timeframe import TimeFrame
from datetime import datetime
import pandas as pd

# Initialize the client with authentication
client = StockHistoricalDataClient(
    api_key="PKQ56JJQ6LBTW25T76ZMXRIAN6",
    secret_key="CPCt567h6ZgPKxm49zFA3mgNGU2JK4HhaHdEvqdUUSxo"
)

# Define parameters
# symbols = ["SPXU", "UPRO", "GDXU"]
symbols = ["SPY"]
start_date = datetime(2020, 12, 10)
end_date = datetime(2025, 12, 12)

# Create request
request_params = StockBarsRequest(
    symbol_or_symbols=symbols,
    timeframe=TimeFrame.Minute,  # Can be Minute, Hour, Day, Week, Month
    start=start_date,
    end=end_date,
    adjustment="split"
)

# Get the data
bars = client.get_stock_bars(request_params)

# Convert to DataFrame
df = bars.df

# If you want separate DataFrames per symbol:
for symbol in symbols:
    symbol_df = df.loc[symbol] if symbol in df.index.get_level_values(0) else pd.DataFrame()
    print(f"\n{symbol}:")
    print(symbol_df.head())

SPY:
                             open    high     low   close  volume  \
timestamp
2020-12-10 00:00:00+00:00  367.48  367.49  367.48  367.49   239.0
2020-12-10 00:03:00+00:00  367.41  367.44  367.41  367.41  1365.0
2020-12-10 00:04:00+00:00  367.41  367.46  367.41  367.46  1095.0
2020-12-10 00:06:00+00:00  367.28  367.36  367.28  367.36   775.0
2020-12-10 00:07:00+00:00  367.38  367.38  367.38  367.38   100.0

                           trade_count        vwap
timestamp
2020-12-10 00:00:00+00:00          5.0  367.485000
2020-12-10 00:03:00+00:00          8.0  367.434691
2020-12-10 00:04:00+00:00          4.0  367.435000
2020-12-10 00:06:00+00:00          9.0  367.318333
2020-12-10 00:07:00+00:00          1.0  367.380000

In [3]:
df

                                      open      high     low     close  \
symbol timestamp
SPY    2020-12-10 00:00:00+00:00  367.4800  367.4900  367.48  367.4900
       2020-12-10 00:03:00+00:00  367.4100  367.4400  367.41  367.4100
       2020-12-10 00:04:00+00:00  367.4100  367.4600  367.41  367.4600
       2020-12-10 00:06:00+00:00  367.2800  367.3600  367.28  367.3600
       2020-12-10 00:07:00+00:00  367.3800  367.3800  367.38  367.3800
...                                    ...       ...     ...       ...
       2025-12-11 23:56:00+00:00  688.8800  688.8800  688.88  688.8800
       2025-12-11 23:57:00+00:00  688.8800  688.8800  688.86  688.8600
       2025-12-11 23:58:00+00:00  688.9000  688.9000  688.90  688.9000
       2025-12-11 23:59:00+00:00  688.9310  688.9500  688.75  688.7500
       2025-12-12 00:00:00+00:00  688.7294  688.7294  688.47  688.4867

                                  volume  trade_count        vwap
symbol timestamp
SPY    2020-12-10 00:00:00+00:00   239.0          5.0  367.485000
       2020-12-10 00:03:00+00:00  1365.0          8.0  367.434691
       2020-12-10 00:04:00+00:00  1095.0          4.0  367.435000
       2020-12-10 00:06:00+00:00   775.0          9.0  367.318333
       2020-12-10 00:07:00+00:00   100.0          1.0  367.380000
...                                  ...          ...         ...
       2025-12-11 23:56:00+00:00  1568.0         21.0  688.880000
       2025-12-11 23:57:00+00:00   525.0         12.0  688.876000
       2025-12-11 23:58:00+00:00   226.0          9.0  688.900000
       2025-12-11 23:59:00+00:00   829.0         42.0  688.829201
       2025-12-12 00:00:00+00:00  3730.0         66.0  688.540768

[1026190 rows x 7 columns]

In [5]:
df_fixed = df.reset_index()
df_fixed["timestamp"]=df_fixed['timestamp'].dt.tz_convert('US/Eastern')
df_fixed.to_csv("e:\\programming\\trading_guy\\data\\GDXU_1min.csv", index=False)
df_fixed

,symbol,timestamp,open,high,low,close,volume,trade_count,vwap
0,GDXU,2020-12-10 08:30:00-05:00,270.00,270.00,270.00,270.00,10.0,1.0,270.00
1,GDXU,2020-12-10 09:30:00-05:00,242.00,242.00,242.00,242.00,56.0,5.0,242.00
2,GDXU,2020-12-10 09:34:00-05:00,239.20,241.20,239.20,241.20,50.0,7.0,240.40
3,GDXU,2020-12-10 09:38:00-05:00,242.00,242.00,242.00,242.00,200.0,2.0,242.00
4,GDXU,2020-12-10 09:40:00-05:00,244.00,244.00,243.70,243.80,55.0,5.0,243.84
...,...,...,...,...,...,...,...,...,...
392907,GDXU,2025-12-11 18:15:00-05:00,250.50,250.50,250.50,250.50,1007.0,5.0,250.50
392908,GDXU,2025-12-11 18:16:00-05:00,250.49,250.49,250.49,250.49,102.0,3.0,250.49
392909,GDXU,2025-12-11 18:19:00-05:00,250.19,250.19,250.19,250.19,153.0,3.0,250.19
392910,GDXU,2025-12-11 18:34:00-05:00,248.99,248.99,248.99,248.99,681.0,8.0,248.99
392911,GDXU,2025-12-11 18:37:00-05:00,248.29,248.29,248.29,248.29,201.0,5.0,248.29

In [6]:
import pandas as pd

df_fixed.to_csv("e:\\programming\\trading_guy\\data\\GDXU_1min.csv", index=False)

######################## End of Downloader Code ######################

########################Aggregating Pandas df with multiple symbols to 5 mins instead ##############

In [7]:
import pandas as pd

df = pd.read_csv("e:\\programming\\trading_guy\\data\\GDXU_1min.csv", parse_dates=['timestamp'])
df

,symbol,timestamp,open,high,low,close,volume,trade_count,vwap
0,GDXU,2020-12-10 08:30:00-05:00,270.00,270.00,270.00,270.00,10.0,1.0,270.00
1,GDXU,2020-12-10 09:30:00-05:00,242.00,242.00,242.00,242.00,56.0,5.0,242.00
2,GDXU,2020-12-10 09:34:00-05:00,239.20,241.20,239.20,241.20,50.0,7.0,240.40
3,GDXU,2020-12-10 09:38:00-05:00,242.00,242.00,242.00,242.00,200.0,2.0,242.00
4,GDXU,2020-12-10 09:40:00-05:00,244.00,244.00,243.70,243.80,55.0,5.0,243.84
...,...,...,...,...,...,...,...,...,...
392907,GDXU,2025-12-11 18:15:00-05:00,250.50,250.50,250.50,250.50,1007.0,5.0,250.50
392908,GDXU,2025-12-11 18:16:00-05:00,250.49,250.49,250.49,250.49,102.0,3.0,250.49
392909,GDXU,2025-12-11 18:19:00-05:00,250.19,250.19,250.19,250.19,153.0,3.0,250.19
392910,GDXU,2025-12-11 18:34:00-05:00,248.99,248.99,248.99,248.99,681.0,8.0,248.99
392911,GDXU,2025-12-11 18:37:00-05:00,248.29,248.29,248.29,248.29,201.0,5.0,248.29

In [9]:
from utils.utils import aggregate_stock_data
df['timestamp'] = pd.to_datetime(df['timestamp'], utc=True)
df_5min = aggregate_stock_data(df, "5min")

df_5min["timestamp"]=df_5min['timestamp'].dt.tz_convert('US/Eastern')

df_5min.to_csv("e:\\programming\\trading_guy\\data\\GDXU_5min.csv", index=False)
df_5min

In [ ]:
df_5min.loc[df_5min["symbol"] == "GDXU"]

In [ ]:
#df_fixed = df_5min.reset_index()
df_one_symbol = df_5min.loc[df_5min["symbol"] == "SPXU"]
df_one_symbol.to_csv("e:\\programming\\trading_guy\\data\\SPXU_5min.csv", index=False)
df_one_symbol

########################### Aggregation done #############################

######################### Filter to Market Hours #############################

In [16]:
from datetime import time

market_open = time(9, 30)
market_close = time(16, 0)

df_market_hours = df_5min[
  (df_5min['timestamp'].dt.time >= market_open) &
  (df_5min['timestamp'].dt.time < market_close)
]
df_market_hours.to_csv("e:\\programming\\trading_guy\\data\\GDXU_5min_MarketHours.csv", index=False)
df_market_hours

,timestamp,open,high,low,close,volume,trade_count,symbol
1,2020-12-10 09:30:00-05:00,242.0000,242.000,242.00,242.0000,56.0,5.0,GDXU
2,2020-12-10 09:35:00-05:00,239.2000,241.200,239.20,241.2000,50.0,7.0,GDXU
3,2020-12-10 09:40:00-05:00,242.0000,244.000,242.00,243.8000,255.0,7.0,GDXU
4,2020-12-10 09:45:00-05:00,244.2000,245.600,244.20,245.4500,60.0,3.0,GDXU
5,2020-12-10 09:55:00-05:00,246.9000,246.900,246.00,246.0000,70.0,5.0,GDXU
...,...,...,...,...,...,...,...,...
129062,2025-12-11 15:35:00-05:00,250.3050,250.600,250.04,250.6000,1168.0,38.0,GDXU
129063,2025-12-11 15:40:00-05:00,250.5001,251.000,250.25,251.0000,5197.0,105.0,GDXU
129064,2025-12-11 15:45:00-05:00,250.9500,251.350,250.80,251.3500,3261.0,89.0,GDXU
129065,2025-12-11 15:50:00-05:00,250.8800,251.064,249.32,249.7725,26980.0,171.0,GDXU
129066,2025-12-11 15:55:00-05:00,250.0000,250.715,249.25,249.9123,10607.0,259.0,GDXU

################# Code to prepare barchart data for use ######################

In [11]:
import pandas as pd

df = pd.read_csv("e:\\programming\\trading_guy\\data\\barchart\\GDXU.csv")
df_a = df.rename(columns={
    "Time":"timestamp", "Open": "open", "High": "high", "Low": "low", "Last": "close", "Volume": "volume",
    "Change": "trade_count"
    })
df_a['symbol'] = "GDXU"
df_a = df_a.drop("%Chg", axis=1)
df_a

,timestamp,open,high,low,close,trade_count,volume,symbol
0,2025-09-05 15:55,136.75,136.9099,136.5200,136.690,0.310,11624,GDXU
1,2025-09-05 15:50,136.30,136.7500,136.3000,136.380,0.220,9772,GDXU
2,2025-09-05 15:45,136.00,136.3000,135.7600,136.160,0.270,2469,GDXU
3,2025-09-05 15:40,135.99,136.0100,135.7614,135.890,0.130,6545,GDXU
4,2025-09-05 15:35,135.97,135.9700,135.7600,135.760,-0.275,600,GDXU
...,...,...,...,...,...,...,...,...
88107,2020-12-03 10:30,240.50,240.5000,240.5000,240.500,1.200,10,GDXU
88108,2020-12-03 10:25,239.30,239.3000,239.3000,239.300,0.100,10,GDXU
88109,2020-12-03 10:00,237.80,239.2000,237.6000,239.200,1.200,50,GDXU
88110,2020-12-03 09:55,238.00,238.0000,238.0000,238.000,-1.599,20,GDXU
88111,2020-12-03 09:45,240.00,240.0000,239.5990,239.599,-3.501,30,GDXU

In [12]:
# Fix timestamp format to match required format: 2022-01-03 10:30:00+00:00
df_a['timestamp'] = pd.to_datetime(df_a['timestamp'], format='%Y-%m-%d %H:%M')
df_a['timestamp'] = df_a['timestamp'].dt.tz_localize('UTC')

print("Timestamp format fixed:")
print(df_a['timestamp'].head())
print(f"\nExample timestamp: {df_a['timestamp'].iloc[0]}")

Timestamp format fixed:
0   2025-09-05 15:55:00+00:00
1   2025-09-05 15:50:00+00:00
2   2025-09-05 15:45:00+00:00
3   2025-09-05 15:40:00+00:00
4   2025-09-05 15:35:00+00:00
Name: timestamp, dtype: datetime64[ns, UTC]

Example timestamp: 2025-09-05 15:55:00+00:00

In [13]:
# Save the corrected dataframe with proper timestamp format
df_a.to_csv("e:\\programming\\trading_guy\\data\\barchart\\GDXU_fixed.csv", index=False)
print("Saved corrected data to GDXU_fixed.csv")

Saved corrected data to GDXU_fixed.csv

######################### End of Code to fix barchart data files ###########################

In [36]:
df_fixed["timestamp"]=df_fixed['timestamp'].dt.tz_convert('US/Eastern')
df_fixed = df_fixed.drop('timestamp_et', axis=1)
df_fixed

,symbol,timestamp,open,high,low,close,volume,trade_count,vwap
0,GDXU,2025-12-09 19:16:00-05:00,211.3800,211.3800,211.3800,211.3800,150.0,2.0,211.3800
1,GDXU,2025-12-09 19:23:00-05:00,211.1000,211.1000,211.1000,211.1000,180.0,2.0,211.1000
2,GDXU,2025-12-09 19:38:00-05:00,211.4000,211.4000,211.4000,211.4000,3462.0,4.0,211.4000
3,GDXU,2025-12-09 19:48:00-05:00,211.3001,211.3001,211.3001,211.3001,127.0,2.0,211.3001
4,GDXU,2025-12-09 19:49:00-05:00,211.5000,211.5000,211.5000,211.5000,385.0,7.0,211.5000
...,...,...,...,...,...,...,...,...,...
3352,UPRO,2025-12-11 18:44:00-05:00,119.5800,119.5800,119.5800,119.5800,489.0,5.0,119.5800
3353,UPRO,2025-12-11 18:48:00-05:00,119.6200,119.6200,119.6200,119.6200,1300.0,5.0,119.6200
3354,UPRO,2025-12-11 18:49:00-05:00,119.6200,119.6200,119.6200,119.6200,1311.0,7.0,119.6200
3355,UPRO,2025-12-11 18:51:00-05:00,119.5625,119.5625,119.5625,119.5625,140.0,2.0,119.5625
3356,UPRO,2025-12-11 18:55:00-05:00,119.5500,119.5500,119.5500,119.5500,432.0,3.0,119.5500

In [37]:
from datetime import time

market_open = time(9, 30)
market_close = time(16, 0)

df_market_hours = df_fixed[
  (df_fixed['timestamp'].dt.time >= market_open) &
  (df_fixed['timestamp'].dt.time < market_close)
]
df_market_hours

,symbol,timestamp,open,high,low,close,volume,trade_count,vwap
32,GDXU,2025-12-10 09:30:00-05:00,210.6200,211.5600,209.3500,209.4464,10680.0,192.0,210.580965
33,GDXU,2025-12-10 09:31:00-05:00,210.8482,213.5250,210.8482,213.5250,11072.0,176.0,212.885098
34,GDXU,2025-12-10 09:32:00-05:00,213.2700,213.2700,210.5300,210.5300,3100.0,58.0,212.316501
35,GDXU,2025-12-10 09:33:00-05:00,211.3200,211.3200,209.0000,209.0000,3027.0,83.0,209.343333
36,GDXU,2025-12-10 09:35:00-05:00,209.0000,209.1092,208.3100,209.1092,1931.0,46.0,208.751179
...,...,...,...,...,...,...,...,...,...
3262,UPRO,2025-12-11 15:55:00-05:00,119.4300,119.4700,119.3100,119.3200,93855.0,857.0,119.413630
3263,UPRO,2025-12-11 15:56:00-05:00,119.3050,119.3300,119.1700,119.2300,103547.0,685.0,119.255758
3264,UPRO,2025-12-11 15:57:00-05:00,119.2400,119.4100,119.2200,119.3800,55495.0,419.0,119.345472
3265,UPRO,2025-12-11 15:58:00-05:00,119.3900,119.5550,119.3800,119.5400,187983.0,1321.0,119.503316
3266,UPRO,2025-12-11 15:59:00-05:00,119.5450,119.6800,119.4600,119.6600,231068.0,1663.0,119.537889

In [38]:
df_market_hours.to_csv("e:\\programming\\trading_guy\\data\\barchart\\GDXU_fixed_market_hours.csv", index=False)