In [2]:
from alpaca.data.historical import StockHistoricalDataClient
from alpaca.data.requests import StockBarsRequest
from alpaca.data.timeframe import TimeFrame
from datetime import datetime
import pandas as pd

# Initialize the client with authentication
client = StockHistoricalDataClient(
    api_key="PKV3XO6QT0D3QB4LAYTQ",
    secret_key="zl4yakxRfMGVUvfB8zfux9xhpfbCv1oAQM8UhSW8"
)

# Define parameters
symbols = ["AAPL", "MSFT", "GOOGL", "TSLA"]
start_date = datetime(2024, 1, 1)
end_date = datetime(2024, 12, 31)

# Create request
request_params = StockBarsRequest(
    symbol_or_symbols=symbols,
    timeframe=TimeFrame.Day,  # Can be Minute, Hour, Day, Week, Month
    start=start_date,
    end=end_date
)

# Get the data
bars = client.get_stock_bars(request_params)

# Convert to DataFrame
df = bars.df

# If you want separate DataFrames per symbol:
for symbol in symbols:
    symbol_df = df.loc[symbol] if symbol in df.index.get_level_values(0) else pd.DataFrame()
    print(f"\n{symbol}:")
    print(symbol_df.head())

AAPL:
                              open      high      low   close      volume  \
timestamp
2024-01-02 05:00:00+00:00  187.150  188.4400  183.885  185.64  82496943.0
2024-01-03 05:00:00+00:00  184.220  185.8800  183.430  184.25  58418916.0
2024-01-04 05:00:00+00:00  182.150  183.0872  180.880  181.91  71992243.0
2024-01-05 05:00:00+00:00  181.990  182.7600  180.170  181.18  62379661.0
2024-01-08 05:00:00+00:00  182.085  185.6000  181.500  185.56  59151720.0

                           trade_count        vwap
timestamp
2024-01-02 05:00:00+00:00    1009074.0  185.846233
2024-01-03 05:00:00+00:00     656956.0  184.319693
2024-01-04 05:00:00+00:00     712850.0  182.013085
2024-01-05 05:00:00+00:00     682335.0  181.483937
2024-01-08 05:00:00+00:00     669304.0  184.400869

MSFT:
                              open      high      low   close      volume  \
timestamp
2024-01-02 05:00:00+00:00  373.860  375.9000  366.771  370.87  25263217.0
2024-01-03 05:00:00+00:00  369.010  373.2562  368.510  370.60  23087200.0
2024-01-04 05:00:00+00:00  370.665  373.1000  367.170  367.94  20903636.0
2024-01-05 05:00:00+00:00  368.970  372.0600  366.500  367.75  21004575.0
2024-01-08 05:00:00+00:00  369.300  375.2000  369.010  374.69  23138403.0

                           trade_count        vwap
timestamp
2024-01-02 05:00:00+00:00     458201.0  370.084432
2024-01-03 05:00:00+00:00     373471.0  371.174093
2024-01-04 05:00:00+00:00     336285.0  369.696686
2024-01-05 05:00:00+00:00     327543.0  368.891836
2024-01-08 05:00:00+00:00     370117.0  373.006602

GOOGL:
                              open      high     low   close      volume  \
timestamp
2024-01-02 05:00:00+00:00  138.550  139.4500  136.48  138.17  23715274.0
2024-01-03 05:00:00+00:00  137.250  139.6300  137.08  138.92  24214076.0
2024-01-04 05:00:00+00:00  138.420  139.1600  136.35  136.39  27139644.0
2024-01-05 05:00:00+00:00  136.745  137.1558  135.15  135.73  22513854.0
2024-01-08 05:00:00+00:00  136.290  139.0100  136.26  138.84  21405420.0

                           trade_count        vwap
timestamp
2024-01-02 05:00:00+00:00     314071.0  137.757757
2024-01-03 05:00:00+00:00     271715.0  138.749284
2024-01-04 05:00:00+00:00     278870.0  137.364563
2024-01-05 05:00:00+00:00     254931.0  136.022865
2024-01-08 05:00:00+00:00     251527.0  138.104058

TSLA:
                             open      high       low   close       volume  \
timestamp
2024-01-02 05:00:00+00:00  250.08  251.2500  244.4100  248.42  104677350.0
2024-01-03 05:00:00+00:00  244.98  245.6800  236.3200  238.45  121104606.0
2024-01-04 05:00:00+00:00  239.25  242.7000  237.7300  237.93  102645460.0
2024-01-05 05:00:00+00:00  236.86  240.1196  234.9001  237.49   92488939.0
2024-01-08 05:00:00+00:00  236.14  241.2500  235.3000  240.45   85180396.0

                           trade_count        vwap
timestamp
2024-01-02 05:00:00+00:00    1178077.0  248.350303
2024-01-03 05:00:00+00:00    1274176.0  239.769658
2024-01-04 05:00:00+00:00    1001894.0  240.359483
2024-01-05 05:00:00+00:00     934668.0  237.932390
2024-01-08 05:00:00+00:00     971097.0  238.603202

In [20]:
df

                                     open      high      low   close  \
symbol timestamp
MSFT   2024-01-02 05:00:00+00:00  373.860  375.9000  366.771  370.87
       2024-01-03 05:00:00+00:00  369.010  373.2562  368.510  370.60
       2024-01-04 05:00:00+00:00  370.665  373.1000  367.170  367.94
       2024-01-05 05:00:00+00:00  368.970  372.0600  366.500  367.75
       2024-01-08 05:00:00+00:00  369.300  375.2000  369.010  374.69
...                                   ...       ...      ...     ...
GOOGL  2024-12-23 05:00:00+00:00  192.620  195.1000  190.150  194.63
       2024-12-24 05:00:00+00:00  194.840  196.1100  193.780  196.11
       2024-12-26 05:00:00+00:00  195.150  196.7480  194.375  195.60
       2024-12-27 05:00:00+00:00  194.950  195.3200  190.650  192.76
       2024-12-30 05:00:00+00:00  189.800  192.5500  189.120  191.24

                                      volume  trade_count        vwap
symbol timestamp
MSFT   2024-01-02 05:00:00+00:00  25263217.0     458201.0  370.084432
       2024-01-03 05:00:00+00:00  23087200.0     373471.0  371.174093
       2024-01-04 05:00:00+00:00  20903636.0     336285.0  369.696686
       2024-01-05 05:00:00+00:00  21004575.0     327543.0  368.891836
       2024-01-08 05:00:00+00:00  23138403.0     370117.0  373.006602
...                                      ...          ...         ...
GOOGL  2024-12-23 05:00:00+00:00  25675014.0     310992.0  193.585438
       2024-12-24 05:00:00+00:00  10403259.0     155818.0  195.502597
       2024-12-26 05:00:00+00:00  12057210.0     196317.0  195.804373
       2024-12-27 05:00:00+00:00  18891362.0     284116.0  192.436699
       2024-12-30 05:00:00+00:00  14264659.0     255690.0  191.190386

[1004 rows x 7 columns]

In [22]:
 timestamp = "2024-01-11 05:00:00+00:00"
 day_data = df.xs(timestamp, level='timestamp')
 day_data

          open    high      low   close       volume  trade_count        vwap
symbol
MSFT    386.00  390.68  380.380  384.63   27855837.0     463131.0  384.636980
TSLA    230.57  230.93  225.370  227.22  105925601.0    1267362.0  227.453305
AAPL    186.54  187.05  183.620  185.59   49133996.0     584114.0  185.022217
GOOGL   143.49  145.22  140.635  142.08   24012786.0     318803.0  142.317740

In [39]:
import sys
sys.path.insert(0, '..')
from core.classes import PriceData

data = bars.data
counters = {}
for symbol in bars.data.keys():
    counters[symbol] = 0

for ts in df.index.get_level_values('timestamp').unique().sort_values():
    vals = {}
    pt = ts.to_pydatetime()
    for symbol in data.keys():



    break

2024-01-02 05:00:00+00:00
<class 'datetime.datetime'>

In [ ]:
counters = {}
for symbol in bars.data.keys():
    counters[symbol] = 0

data_available = True
while data_available:
    for symbol in bars.data.keys():

In [30]:
bars.data['MSFT'][0].timestamp

datetime.datetime(2024, 1, 2, 5, 0, tzinfo=TzInfo(UTC))

In [16]:
symbol = "AAPL"
symbol_df = df.loc[symbol] if symbol in df.index.get_level_values(0) else pd.DataFrame()
symbol_df["symbol"] = symbol
symbol_df

/var/folders/9j/r33gzcz11018_z_5224w5nph0000gn/T/ipykernel_8985/394353668.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  symbol_df["symbol"] = symbol

,open,high,low,close,volume,trade_count,vwap,symbol
timestamp,,,,,,,,
2024-01-02 05:00:00+00:00,187.150,188.4400,183.885,185.64,82496943.0,1009074.0,185.846233,AAPL
2024-01-03 05:00:00+00:00,184.220,185.8800,183.430,184.25,58418916.0,656956.0,184.319693,AAPL
2024-01-04 05:00:00+00:00,182.150,183.0872,180.880,181.91,71992243.0,712850.0,182.013085,AAPL
2024-01-05 05:00:00+00:00,181.990,182.7600,180.170,181.18,62379661.0,682335.0,181.483937,AAPL
2024-01-08 05:00:00+00:00,182.085,185.6000,181.500,185.56,59151720.0,669304.0,184.400869,AAPL
...,...,...,...,...,...,...,...,...
2024-12-23 05:00:00+00:00,254.770,255.6500,253.450,255.27,40858774.0,422563.0,254.713849,AAPL
2024-12-24 05:00:00+00:00,255.490,258.2100,255.290,258.20,23234705.0,245932.0,257.452942,AAPL
2024-12-26 05:00:00+00:00,258.190,260.1000,257.630,259.02,27262983.0,362325.0,258.937766,AAPL
2024-12-27 05:00:00+00:00,257.830,258.7000,253.060,255.59,42355321.0,474899.0,255.255129,AAPL
2024-12-30 05:00:00+00:00,252.230,253.5000,250.750,252.20,35557542.0,421634.0,252.228327,AAPL

In [14]:
df.iloc[0]

open           3.738600e+02
high           3.759000e+02
low            3.667710e+02
close          3.708700e+02
volume         2.526322e+07
trade_count    4.582010e+05
vwap           3.700844e+02
Name: (MSFT, 2024-01-02 05:00:00+00:00), dtype: float64

In [8]:
df

                                     open      high      low   close  \
symbol timestamp
MSFT   2024-01-02 05:00:00+00:00  373.860  375.9000  366.771  370.87
       2024-01-03 05:00:00+00:00  369.010  373.2562  368.510  370.60
       2024-01-04 05:00:00+00:00  370.665  373.1000  367.170  367.94
       2024-01-05 05:00:00+00:00  368.970  372.0600  366.500  367.75
       2024-01-08 05:00:00+00:00  369.300  375.2000  369.010  374.69
...                                   ...       ...      ...     ...
GOOGL  2024-12-23 05:00:00+00:00  192.620  195.1000  190.150  194.63
       2024-12-24 05:00:00+00:00  194.840  196.1100  193.780  196.11
       2024-12-26 05:00:00+00:00  195.150  196.7480  194.375  195.60
       2024-12-27 05:00:00+00:00  194.950  195.3200  190.650  192.76
       2024-12-30 05:00:00+00:00  189.800  192.5500  189.120  191.24

                                      volume  trade_count        vwap
symbol timestamp
MSFT   2024-01-02 05:00:00+00:00  25263217.0     458201.0  370.084432
       2024-01-03 05:00:00+00:00  23087200.0     373471.0  371.174093
       2024-01-04 05:00:00+00:00  20903636.0     336285.0  369.696686
       2024-01-05 05:00:00+00:00  21004575.0     327543.0  368.891836
       2024-01-08 05:00:00+00:00  23138403.0     370117.0  373.006602
...                                      ...          ...         ...
GOOGL  2024-12-23 05:00:00+00:00  25675014.0     310992.0  193.585438
       2024-12-24 05:00:00+00:00  10403259.0     155818.0  195.502597
       2024-12-26 05:00:00+00:00  12057210.0     196317.0  195.804373
       2024-12-27 05:00:00+00:00  18891362.0     284116.0  192.436699
       2024-12-30 05:00:00+00:00  14264659.0     255690.0  191.190386

[1004 rows x 7 columns]